---
name: 'Greetings'

# yamllint disable-line rule:truthy
on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/first-interaction@v1
      # yamllint disable-line rule:comments-indentation
      # TODO: // FIX ONCE THE COMMUNITY ACTION HAS AN UPDATE
      # https://github.com/actions/first-interaction/issues/101
        continue-on-error: true
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: 'Thank you for creating an Issue.'
          pr-message: 'Thank you for making a PR.'
